package eg.bahr.buildlogic

import com.diffplug.gradle.spotless.SpotlessExtension
import kotlinx.kover.gradle.plugin.dsl.KoverProjectExtension
import org.gradle.api.GradleException
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure

/**
 * `bahr.root`, applied once to the root project:
 *  - Spotless for the root build scripts and build-logic itself (modules format their own);
 *  - the merged Kover report and gate (`koverHtmlReportMobile` / `koverXmlReportMobile` /
 *    `koverVerifyMobile`), part of `check`;
 *  - `installGitHooks`.
 */
class RootConventionPlugin : Plugin<Project> {
    override fun apply(target: Project): Unit =
        with(target) {
            pluginManager.apply("base") // the `check` lifecycle task for a root that compiles nothing
            configureRootSpotless()
            configureMergedCoverage()
            registerInstallGitHooks()
        }
}

/**
 * Raised as coverage grows; never set above what `koverHtmlReportMobile` measures.
 * Measured 74.7 % line (713/955) at M0-M4.
 */
private const val KOVER_MIN_LINE_PERCENT = 74

private fun Project.configureRootSpotless() {
    pluginManager.apply("com.diffplug.spotless")
    val ktlintVersion = libs.version("ktlint")
    extensions.configure<SpotlessExtension> {
        // build-logic is an included build, not a subproject, so the root formats it. File trees
        // rooted at build-logic/src keep Spotless from walking the rest of the repository.
        bahrKotlin(ktlintVersion, fileTree("build-logic/src") { include("**/*.kt") })
        bahrKotlinGradle(ktlintVersion, "*.gradle.kts", "build-logic/*.gradle.kts")
    }
    tasks.named("check") { dependsOn("spotlessCheck") }
}

/**
 * Scope per PLAN §11: core:* plus view models. Every `core:*` and `feature:*` module applies a
 * convention that contributes a `mobile` variant (see Kover.kt), so a new module is counted
 * without anyone listing it here.
 */
private fun Project.configureMergedCoverage() {
    pluginManager.apply("org.jetbrains.kotlinx.kover")
    subprojects
        .filter { it.path.startsWith(":core:") || it.path.startsWith(":feature:") }
        .forEach { dependencies.add("kover", it) }

    extensions.configure<KoverProjectExtension> {
        currentProject { createVariant(COVERAGE_VARIANT) {} }
        reports {
            filters {
                includes {
                    classes("eg.bahr.core.*", "*ViewModel", "*ViewModel$*")
                }
                excludes {
                    // Generated by compose-resources and the Compose compiler; not our code.
                    classes("*.generated.resources.*", "*ComposableSingletons*", "*.BuildConfig")
                    // Test helpers, shipped only to other modules' test source sets.
                    classes("eg.bahr.core.testing.*")
                }
            }
            // Gate at the measured level (see README.md → Testing), so coverage can only go up.
            verify {
                rule {
                    minBound(KOVER_MIN_LINE_PERCENT)
                }
            }
        }
    }
    tasks.named("check") { dependsOn("koverVerifyMobile") }
}

/** Run once after cloning. The hook runs spotlessCheck on commit and points at spotlessApply. */
private fun Project.registerInstallGitHooks() {
    tasks.register("installGitHooks") {
        group = "git hooks"
        description = "Copy scripts/git-hooks/pre-commit into .git/hooks/."
        val source = file("scripts/git-hooks/pre-commit")
        val destination = file(".git/hooks/pre-commit")
        inputs.file(source)
        outputs.file(destination)
        doLast {
            if (!source.exists()) {
                throw GradleException("Missing $source — check it into the repo first.")
            }
            destination.parentFile.mkdirs()
            source.copyTo(destination, overwrite = true)
            destination.setExecutable(true)
            println("Installed pre-commit hook at $destination")
        }
    }
}
